import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home / صفحهٰ اصلی</title>
        <meta name="description" content="Mohsen Shabanian Webpage" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className='animated-hover-underline'>
          <ul className='h-screen flex flex-col justify-around persian-font'>
            <li className='text-center'><Link href="/about">About / دربارهٔ من</Link></li>
            <li className='text-center'><Link href="/portfolios">Portfolios / نمونه کار</Link></li>
            <li className='text-center'><Link href="/blog">Blog / نوشته‌ها</Link></li>
            <li className='text-center'><Link href="/memory">Memory / خاطرات</Link></li>
            <li className='text-center'><Link href="/story">Story / داستانک</Link></li>
            <li className='text-center'>
              {/* <a href="http://youtube.com" target="_blank" rel="noopener noreferrer"><Image src="/img/svg//youtube-brands.svg" alt="youtube Logo" width={40} height={16} /></a> */}
              <a href="http://linkdin.com/in/mohsenshabanian" target="_blank" title='linkdin account' rel="noopener noreferrer"><Image src="/img/svg/linkedin-brands.svg" alt="linkedin Logo" width={40} height={16} /></a>
              <a href="mailto:info@MohsenShabanian.com" target="_blank" title='email' rel="noopener noreferrer"><Image src="/img/svg/envelope-solid.svg" alt="envelope" width={40} height={16} /></a>
              <a href="tel:+989113923310" target="_blank" title='mobile' rel="noopener noreferrer"><Image src="/img/svg/phone-solid.svg" alt="phone" width={40} height={16} /></a>
              <a href="http://twitter.com/mohsen1299" target="_blank" title='twitter account' rel="noopener noreferrer"><Image src="/img/svg/twitter-brands.svg" alt="twitter Logo" width={40} height={16} /></a>
              <a href="/assets/Resume_MohsenShabanian.pdf" title='resume file' download="resume file"><Image src="/img/svg/file-pdf-solid.svg" alt="resume file" width={40} height={16} /></a>
              </li>
          </ul>
        </nav>
      </main>
    </div>
  )
}

export default Home

/*
<Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      */